### ISSUE TITLE
Statistics are not working

### ISSUE THREAD

**Issue by hanu7674** [rhalp10/TracerStudy-System#10]
The stastic.php is not working

The try.php or tr1.php or try2.php are could not show the information in graphical format when I selected as pie, bar, or doughnut.

Could you please explain this issue?

**Comment by rhalp10** [comment]
@hanu7674  because chart.js dist is missing `<script src="assets/lib/chart-master/dist/Chart.bundle.js"></script> `  
Fix: c42dd036f203038595991fd7def2c1764484957b
