### ISSUE TITLE
Fatal error: Call to undefined function mcrypt_encrypt()

### ISSUE THREAD

**Issue by hanu7674** [rhalp10/TracerStudy-System#9]
Fatal error: Call to undefined function mcrypt_encrypt() on md5,php

**Comment by rhalp10** [comment]
> Fatal error: Call to undefined function mcrypt_encrypt() on md5,php

you need to use "**PHP 7.1.0**" this was already removed and deprecated as of "**PHP 7.2.0**" see it [here](https://www.php.net/manual/en/function.mcrypt-encrypt.php).
